const quotes = [
  "Every empire begins with a single page.",
  "Fortune favors the well-read.",
  "Read boldly. Invest wisely.",
  "Every book is a new investment.",
  "A good story always pays dividends.",
  "Don't spend all your Baddie Bucks in one place.",
  "The richest readers never skip a chapter.",
  "A full bookshelf is worth more than gold.",
  "Books appreciate faster than real estate.",
  "I've seen worse investment strategies...",
  "Great fortunes begin with great stories.",
  "Every page turned is money well spent.",
  "Another day, another portfolio to manage.",
  "The market may fluctuate, but a good book never goes out of style.",
  "The best investments are the ones that never mature.",
  "Knowledge is the most valuable property of all.",
  "The best way to predict the future is to read it.",
  "A good book is a good investment.",
  "The pen is mightier than the sword.",
  "A wise reader is a wealthy reader.",
  "Reading is the best investment you can make in yourself.",
  "A book a day keeps the doctor away.",
  "The more you read, the more you know.",
  "In the world of books, there is no such thing as too much reading.",
  "The best time to start reading is yesterday.",
  "The greatest wealth is the wealth of knowledge.",
  "The best way to hold onto your money is to read it.",
  "A library is a treasure trove of knowledge and wisdom.",
  "The only thing you need to know is what you don't know.",
  "The best way to predict the future is to read it.",
  "The future belongs to those who read today.",
  "In the library of life, every book is a new chapter.",
  "The pages of your life are written by the books you read.",
  "A good reader is a successful reader.",
  "The right book at the right time can change everything.",
  "Reading changes the way you see the world.",
  "A book is a device to store the knowledge of the ages.",
  "The wisdom of the ages is preserved in the pages of books.",
  "A good book is a good friend.",
  "The best books are the ones that stay with you forever.",
  "A great book can transport you to another world.",
  "The joy of reading is the joy of discovering something new.",
  "A book that changes your life is a book that changes the world.",
  "The power of a good book is in the pages that change your life.",
  "A book that opens your mind opens your heart.",
  "The best books are the ones that challenge your mind and touch your soul.",
  "A book that inspires you to be a better person is a book that changes the world.",
  "The greatest books are the ones that teach you how to think for yourself.",
  "A book that challenges your beliefs is a book that helps you grow.",
  "The most important book you will ever read is the one that changes your perspective.",
  "A book that broadens your horizons opens the door to new possibilities.",
  "Hey...are you actually reading right now?",
  "This message has been approved by absolutely nobody.",
  "Using commands instead of reading? Interesting strategy.",
  "Imagine if you finished another chapter...",
  "Mrs. Bookopoly believes in you. Mostly.",
  "Don't forget to hydrate...and by hydrate I mean read.",
  "Don't spend it all in one place.",
  "Your TBR is judging you...and so am I.",
  "Have you bullied your friends into joining yet?",
  "Books don't read themselves, bestie.",
"I've seen your TBR...we should talk.",
"You've spent more time here than in your book.",
"Reading is highly recommended. Just saying.",
"I'm legally required to encourage reading. So...go read.",
"Closing this embed won't make your TBR disappear.",
"Every command could've been another page read.",
"Don't worry, I won't tell your current read you're procrastinating.",
"I hope your book is as committed to you as you are to this bot.",
"Congratulations! You've successfully avoided reading for another minute.",
"Your bookshelf called. It wants attention.",
"If you're waiting for motivation...this is it.",
"Plot twist: the next chapter is actually really good.",
"Somewhere, your current read is feeling neglected.",
"Touch a book. It misses you.",
"At this rate, you'll finish this command before your chapter.",
"I'm not saying you're procrastinating...but your book probably is.",
"Achievement unlocked: Professional Command Clicker.",
"Don't make me send you to Literary Lockup. READ!",
"The pages aren't going to turn themselves.",
"If you've read this far...you could've read another page.",
"I'm in your walls... Just kidding. Probably.",
"Wait...you're still reading these?",
"Congratulations! You found a rare Mrs. Bookopoly quote.",
"Error 404: Reading motivation not found. Please try again."

  
];

function getRandomQuote() {
  return quotes[Math.floor(Math.random() * quotes.length)];
}

module.exports = {
  getRandomQuote,
};